# Generated by Django 4.2.2 on 2023-08-20 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worlds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('progress_point', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('extra_note', models.TextField(blank=True)),
                ('is_pathbreaking', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('will_continue_again', models.BooleanField(default=False)),
                ('task_point', models.IntegerField(default=0)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDoList.worlds')),
            ],
        ),
    ]
