# Generated by Django 4.2.2 on 2023-08-24 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='task',
            name='will_continue_again',
        ),
        migrations.RemoveField(
            model_name='task',
            name='world',
        ),
        migrations.CreateModel(
            name='World_Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ToDoList.task')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDoList.worlds')),
            ],
        ),
    ]
