# Generated by Django 4.2.2 on 2023-08-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0002_remove_task_is_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world_tasks',
            name='tasks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDoList.task'),
        ),
    ]
